name : BuildApp

on:
  merge_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build app
        run: mvn clean install
